version: '3.8'

services:
  db:
    image: postgres:16
    container_name: razorit-db-local
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: YourSecurePassword123
      POSTGRES_DB: razorit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: razorit-api
    restart: always
    volumes:
      - .:/app  # Ensures `alembic.ini` and migrations persist locally
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # MailHog Web UI (view emails)
      - "1025:1025"  # SMTP server
      
volumes:
  postgres_data:
